<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/page.proto

namespace Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>common.Page</code>
 */
class Page extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 pageNo = 1;</code>
     */
    private $pageNo = 0;
    /**
     * Generated from protobuf field <code>int32 pageSize = 2;</code>
     */
    private $pageSize = 0;
    /**
     * Generated from protobuf field <code>string keyword = 3;</code>
     */
    private $keyword = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $pageNo
     *     @type int $pageSize
     *     @type string $keyword
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Page::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 pageNo = 1;</code>
     * @return int
     */
    public function getPageNo()
    {
        return $this->pageNo;
    }

    /**
     * Generated from protobuf field <code>int32 pageNo = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPageNo($var)
    {
        GPBUtil::checkInt32($var);
        $this->pageNo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pageSize = 2;</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->pageSize;
    }

    /**
     * Generated from protobuf field <code>int32 pageSize = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->pageSize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string keyword = 3;</code>
     * @return string
     */
    public function getKeyword()
    {
        return $this->keyword;
    }

    /**
     * Generated from protobuf field <code>string keyword = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyword($var)
    {
        GPBUtil::checkString($var, True);
        $this->keyword = $var;

        return $this;
    }

}

