<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/page.proto

namespace GPBMetadata\Common;

class Page
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5e0a11636f6d6d6f6e2f706167652e70726f746f1206636f6d6d6f6e22" .
            "390a0450616765120e0a06706167654e6f18012001280512100a08706167" .
            "6553697a65180220012805120f0a076b6579776f72641803200128096206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

