<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users/user.proto

namespace Users;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>users.UserListsReq</code>
 */
class UserListsReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.common.Page page = 1;</code>
     */
    private $page = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Common\Page $page
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Users\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.common.Page page = 1;</code>
     * @return \Common\Page
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>.common.Page page = 1;</code>
     * @param \Common\Page $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkMessage($var, \Common\Page::class);
        $this->page = $var;

        return $this;
    }

}

