<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users/addr.proto

namespace GPBMetadata\Users;

class Addr
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a530a1075736572732f616464722e70726f746f1205757365727322300a" .
            "0441646472120a0a024964180120012805120c0a044e616d651802200128" .
            "09120e0a064d6f62696c65180320012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

