<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users/user.proto

namespace GPBMetadata\Users;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Page::initOnce();
        \GPBMetadata\Users\Addr::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8d020a1075736572732f757365722e70726f746f120575736572731a10" .
            "75736572732f616464722e70726f746f22400a0455736572120a0a024964" .
            "180120012805120c0a044e616d65180220012809121e0a09616464726573" .
            "73657318032003280b320b2e75736572732e41646472222a0a0c55736572" .
            "4c69737473526571121a0a047061676518012001280b320c2e636f6d6d6f" .
            "6e2e50616765222b0a0d557365724c6973747352657370121a0a05757365" .
            "727318012003280b320b2e75736572732e55736572323d0a055573657273" .
            "12340a054c6973747312132e75736572732e557365724c69737473526571" .
            "1a142e75736572732e557365724c69737473526573702200620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

